name: Node CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        env:
          CI: true
          ADMIN_TOKEN: ${{secrets.ADMIN_TOKEN}}
          REACT_APP_WORKSPACE_ID: ${{secrets.WORKSPACE_ID}}
          FIELDWORKER_TOKEN: ${{secrets.FIELDWORKER_TOKEN}}
        run: |
          npm i
          npm run eslint
          npm run build --if-present
          npm run test
